del outfile.tab
call runhfex mv9501 a
call runhfex mv9501 b
call runhfex mv9501 c
call runhfex mv9501 d
call runhfex mv9501 e
call runhfex mv9501 f
call runhfex mv9501 g
call runhfex mv9501 h
call runhfex mv9501 i
call runhfex mv9501 j
rem call runhfex mv9501 k
call runhfex mv9501 l
call runhfex mv9501 m
call runhfex mv9501 n
call runhfex mv9501 o
call runhfex mv9501 p
call runhfex mv9501 q
call runhfex mv9501 r
call runhfex mv9501 s
call runhfex mv9501 t
call runhfex mv9501 u
call runhfex mv9501 v
call runhfex mv9501 w
copy outfile.tab mv9501hf.tab
